"use strict";

const VALID_ACTIONS = [
  "LOGIN",
  "LOGOUT",
  "LOGIN_FAILED",
  "RESIDENT_WEB_LOGIN_BLOCKED",
  "PLATFORM_ACCESS_DENIED",
  "USER_CREATED",
  "USER_UPDATED",
  "USER_DELETED",
  "USER_ROLE_CHANGED",
  "USER_STATUS_CHANGED",
  "USER_VERIFIED",
  "USER_UNVERIFIED",
  "USER_APPROVED",
  "USER_REJECTED",
  "RESIDENT_REGISTRATION_SUBMITTED",
  "APPOINTMENT_CREATED",
  "APPOINTMENT_UPDATED",
  "APPOINTMENT_APPROVED",
  "APPOINTMENT_REJECTED",
  "APPOINTMENT_CANCELLED",
  "APPOINTMENT_RESCHEDULED",
  "APPOINTMENT_PROCESSING",
  "APPOINTMENT_COMPLETED",
  "RECORD_CREATED",
  "RECORD_UPDATED",
  "RECORD_VIEWED",
  "SCHEDULE_CREATED",
  "SCHEDULE_UPDATED",
  "SCHEDULE_DELETED",
  "INVENTORY_ITEM_CREATED",
  "INVENTORY_ITEM_UPDATED",
  "INVENTORY_ITEM_DEACTIVATED",
  "INVENTORY_STOCK_IN",
  "INVENTORY_STOCK_OUT",
  "INVENTORY_ADJUSTED",
  "INVENTORY_EXPIRED_RECORDED",

  "PASSWORD_RESET_REQUESTED",
  "PASSWORD_CHANGED",
];

const VALID_ROLES = ["admin", "doctor", "midwife", "bhw", "resident", "unknown"];

const VALID_SEVERITIES = ["info", "success", "warning", "error"];

module.exports = { VALID_ACTIONS, VALID_ROLES, VALID_SEVERITIES };
