"use strict";

const User = require("../models/User");
const { VALID_STATUSES, resolveUserStatus } = require("../models/User");
const { createSystemLog } = require("../services/systemLogService");
const { describePlatformAccess } = require("../config/platformAccess");
const asyncHandler = require("../utils/asyncHandler");
const { HTTP_STATUS, ERROR_CODES } = require("../utils/errorCodes");
const { isValidObjectId } = require("../utils/objectId");
const { badRequest, forbidden, notFound } = require("../utils/AppError");

/**
 * Adds the fields the admin UI needs but the raw document may not carry:
 * `status` is resolved for accounts written before the field existed, and
 * `phone` is normalised to a string so the client never renders `undefined`.
 *
 * `platformAccess` is computed from the role rather than stored, so the badge
 * User Management shows is generated by the same table the login path
 * enforces and cannot drift from it.
 */
const serializeUser = (user) => ({
  ...user,
  phone: user.phone || "",
  status: resolveUserStatus(user),
  platformAccess: describePlatformAccess(user.role),
  // Null rather than undefined so the field is always present in the payload
  // and the client can tell "never signed in" from "field not sent".
  lastLogin: user.lastLogin || null,
});

exports.getAllUsers = asyncHandler(async (_req, res) => {
  const users = await User.find({})
    .select("-password")
    .sort({ createdAt: -1 })
    .lean();

  return res.status(HTTP_STATUS.OK).json({
    success: true,
    message: "Users loaded successfully.",
    count: users.length,
    users: users.map(serializeUser),
  });
});

/** Past-tense wording for the audit trail, e.g. "activated"/"suspended". */
const STATUS_VERBS = {
  active: "activated",
  inactive: "deactivated",
  pending: "set to pending",
  suspended: "suspended",
};

/**
 * PATCH /users/:id/status — an administrator changes an account's standing.
 *
 * Writes a system log on success so every status change is attributable to
 * the admin who made it.
 */
exports.updateUserStatus = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { status } = req.body;

  if (!isValidObjectId(id)) {
    throw badRequest("A valid user id is required.", ERROR_CODES.VALIDATION_ERROR);
  }

  const nextStatus = typeof status === "string" ? status.trim().toLowerCase() : "";
  if (!VALID_STATUSES.includes(nextStatus)) {
    throw badRequest(
      `Status must be one of: ${VALID_STATUSES.join(", ")}.`,
      ERROR_CODES.VALIDATION_ERROR
    );
  }

  // An admin locking themselves out would leave the system needing direct
  // database access to recover, so it is refused outright.
  const actorId = String(req.user?.userId || req.user?._id || "");
  if (actorId && actorId === String(id) && nextStatus !== "active") {
    throw forbidden(
      "You cannot change your own account status.",
      ERROR_CODES.FORBIDDEN
    );
  }

  const existing = await User.findById(id).select("fullname email role status verified").lean();
  if (!existing) {
    throw notFound("User not found.", ERROR_CODES.USER_NOT_FOUND);
  }

  const previousStatus = resolveUserStatus(existing);

  // A targeted $set rather than load-modify-save: the document is fetched
  // without its password, and running it back through save() would put it
  // through the password-hashing pre-save hook for no reason.
  const user = await User.findByIdAndUpdate(
    id,
    { $set: { status: nextStatus } },
    { new: true, runValidators: true }
  )
    .select("-password")
    .lean();

  // The account could have been removed between the read and the write.
  if (!user) {
    throw notFound("User not found.", ERROR_CODES.USER_NOT_FOUND);
  }

  await createSystemLog({
    req,
    action: "USER_STATUS_CHANGED",
    role: req.user?.role,
    description: `Admin ${STATUS_VERBS[nextStatus]} the account of ${user.fullname}`,
    resource: "User",
    resourceId: String(user._id),
    metadata: {
      targetUserId: String(user._id),
      targetEmail: user.email,
      previousStatus,
      newStatus: nextStatus,
    },
  });

  return res.status(HTTP_STATUS.OK).json({
    success: true,
    message: `User ${STATUS_VERBS[nextStatus]} successfully.`,
    user: serializeUser(user),
  });
});
